### ISSUE TITLE
building-schema error triggered by Google Docs link

### ISSUE THREAD

**Issue by awendland** [cedricdelpoux/gatsby-source-google-docs#103] opened 2021-02-21 01:59 UTC
Hello! First off, thank you so much for making this plugin. It's such a wonderful addition to the workflow for my personal blog.

I've run into a strange error, but I think I've figured out how to reproduce it. First off, here's the error:

> Missing onError handler for invocation 'building-schema', error was 'Invariant Violation: Encountered an error trying to infer a GraphQL type for: `related___NODE`. There is no corresponding node with the `id` field matching: "1ZREDACTED4B-kvY4REDACTEDH4WlEBk".'. Stacktrace was 'Invariant Violation: Encountered an error trying to infer a GraphQL type for: `related___NODE`. There is no corresponding node with the `id` field matching: "1ZREDACTED4B-kvY4REDACTEDH4WlEBk".

And this is what I think causes it:

1. Have `gatsby-source-google-docs` installed and properly configured.
2. Create a Google Doc, Doc1, in the configured source folder.
3. Place a link in Doc1 that points to another Google Doc outside the source folder.
4. Try to build your Gatsby website.

The error disappears once the link has been removed from the doc. The error appears even if the link isn't "hyperlinked", as in, it's just left in the doc as plain text.

The id in my error message, `1ZREDACTED4B-kvY4REDACTEDH4WlEBk`, is the id of the Google Doc I'd linked (e.g. `https://docs.google.com/document/d/1ZREDACTED4B-kvY4REDACTEDH4WlEBk/edit`.

The error causes the build process to hang indefinitely. I've mitigated it for myself by simply no longer referencing the other Google Doc in my source document, but I wanted to share this here in case it affected others and was possible to fix. Please let me know if there's any other details I can provide!

**Comment by linoxyn** [comment] 2021-02-23 22:12
@awendland  I'm pretty sure I have dealt with this very same error. My fix came to me from something else I was editing so I tried it. The paragraph or even just the offending link in your Doc, select it, cut, and 'paste without formatting' or highlight the text/link and remove formatting. This did the trick as I believe the offending link had some differences hidden within the text, of which got removed. Problem solved. Hope that helps? :)

**Comment by cedricdelpoux** [comment] 2021-02-24 07:06
Good catch! You are right, the error should be silent and not stop the build.
If someone want to take a look, PRs are always welcome.

**Comment by cedricdelpoux** [comment] 2021-03-07 08:54
I'm sorry, I tried with links to documents outside the source folder, as plain text or with your url `https://docs.google.com/document/d/1ZREDACTED4B-kvY4REDACTEDH4WlEBk/edit` but I could not reproduce.

So I'm closing now but if you succeed to reproduce, please make a PR with a fix. The code impacted should be [processInternalLinks()](https://github.com/cedricdelpoux/gatsby-source-google-docs/blob/f7ed4c622a58ccdb2bfcd0dff148a8959107c4f8/utils/google-document.js#L491-L509)

**Closed by cedricdelpoux** 2021-03-07 08:54 UTC
Labels: bug, help wanted
