### ISSUE TITLE
Cannot query field "childMarkdownRemark" on type "GoogleDocs"

### ISSUE THREAD

**Issue by BenMini** [cedricdelpoux/gatsby-source-google-docs#93] opened 2020-12-02 18:40 UTC
Unable to find "childMarkdownRemark" or field "document" on type "GoogleDocs". 

Here is my repo: https://github.com/BenMini/test-gatsby-google-plugin

Full Details:
`Debugger listening on ws://127.0.0.1:9229/d2673fec-9375-46dc-b58d-cdde8941c587
For help, see: https://nodejs.org/en/docs/inspector
success open and validate gatsby-configs - 0.027s
success load plugins - 1.582s
success onPreInit - 0.035s
success initialize cache - 0.009s
success copy gatsby files - 0.053s
success onPreBootstrap - 0.017s
success createSchemaCustomization - 0.094s
warn The gatsby-source-google-docs plugin has generated no
success Checking for changed pages - 0.002s
success source and transform nodes - 2.485s
success building schema - 0.332s

 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "document" on type "GoogleDocs".

If you don't expect "document" to exist on the type "GoogleDocs" it is most likely a typo.
However, if you expect "document" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "document" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add at least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "GoogleDocs":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: gatsby-node.js:4:3

 ERROR #11321  PLUGIN

"gatsby-node.js" threw an error while running the createPages lifecycle:

Cannot read property 'allGoogleDocs' of undefined

  15 |     `
  16 |   ).then(result => {
> 17 |     result.data.allGoogleDocs.nodes.forEach(({ document }, index) => {
     |                 ^
  18 |       actions.createPage({
  19 |         path: document.path,
  20 |         component: path.resolve(`./src/templates/post.js`),

File: gatsby-node.js:17:17

  TypeError: Cannot read property 'allGoogleDocs' of undefined

  - gatsby-node.js:17
    /Users/benminifie/Code/PROJECTS/yocal/trial3/gatsby-node.js:    17:17

  - api-runner-node.js:460 runAPI
    [trial3]/[gatsby]/src/utils/api-runner-node.js:460:16

  - From previous event:

  - api-runner-node.js:589 Promise.catch.decorateEvent.pluginNam    e
    [trial3]/[gatsby]/src/utils/api-runner-node.js:589:9

  - From previous event:

  - api-runner-node.js:588
    [trial3]/[gatsby]/src/utils/api-runner-node.js:588:14

  - timers.js:456 processImmediate
    internal/timers.js:456:21

  - From previous event:

  - api-runner-node.js:561
    [trial3]/[gatsby]/src/utils/api-runner-node.js:561:13

  - From previous event:

  - api-runner-node.js:477 module.exports
    [trial3]/[gatsby]/src/utils/api-runner-node.js:477:3

  - create-pages.ts:25 createPages
    [trial3]/[gatsby]/src/services/create-pages.ts:25:9

  - interpreter.js:722 Interpreter.exec
    [trial3]/[xstate]/lib/interpreter.js:722:27

  - interpreter.js:204 Interpreter.execute
    [trial3]/[xstate]/lib/interpreter.js:204:22

  - interpreter.js:224 Interpreter.update
    [trial3]/[xstate]/lib/interpreter.js:224:18

  - interpreter.js:125
    [trial3]/[xstate]/lib/interpreter.js:125:23

  - scheduler.js:60 Scheduler.process
    [trial3]/[xstate]/lib/scheduler.js:60:13

  - scheduler.js:44 Scheduler.schedule
    [trial3]/[xstate]/lib/scheduler.js:44:14

  - interpreter.js:121 Interpreter.send
    [trial3]/[xstate]/lib/interpreter.js:121:29

  - interpreter.js:840 actor.id
    [trial3]/[xstate]/lib/interpreter.js:840:23

info Total nodes: 38, SitePage nodes: 1 (use --verbose for
failed createPages - 0.116s
success Checking for changed pages - 0.001s
success createPagesStatefully - 0.061s
success update schema - 0.027s
success write out redirect data - 0.002s
success Build manifest and related icons - 0.123s
success onPostBootstrap - 0.128s
info bootstrap finished - 7.604s
success onPreExtractQueries - 0.002s
warn Using the global `graphql` tag is deprecated, and will not
be supported in v3.
Import it instead like:  import { graphql } from 'gatsby' in

 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown argument "document" on field "googleDocs" of type "Query".

GraphQL request:3:22
2 |   query($path: String) {
3 |     post: googleDocs(document: { path: { eq: $path } }) {
  |                      ^
4 |       document {

File: src/templates/post.js:11:22

 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "document" on type "GoogleDocs".

If you don't expect "document" to exist on the type "GoogleDocs" it is most likely a typo.
However, if you expect "document" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "document" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add at least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "GoogleDocs":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: src/templates/post.js:12:7

 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "childMarkdownRemark" on type "GoogleDocs".

If you don't expect "childMarkdownRemark" to exist on the type "GoogleDocs" it is most likely a typo.
However, if you expect "childMarkdownRemark" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "childMarkdownRemark" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add at least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "GoogleDocs":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: src/templates/post.js:16:7

failed extract queries from components - 0.446s
success write out requires - 0.007s
success run page queries - 0.029s - 2/2 68.60/s
⠀
You can now view gatsby-starter-default in the browser.
⠀
  http://localhost:8000/
⠀
View GraphiQL, an in-browser IDE, to explore your site's data and schema
⠀
  http://localhost:8000/___graphql
⠀
Note that the development build is not optimized.
To create a production build, use gatsby build
⠀
success Building development bundle - 3.423s`

**Comment by cedricdelpoux** [comment] 2020-12-03 18:28
Hi @BenMini Thank you for reporting this. I will investigate and let you know soon

**Comment by cedricdelpoux** [comment] 2020-12-04 15:22
I think I understood your problem. Documentation was out of date and you tried with an old api to create pages.

I updated the documentation.

Could you try to follow instructions [here](https://github.com/cedricdelpoux/gatsby-source-google-docs/blob/master/docs/pages.md)? 

I close the issue. Feel free to reopen it if the issue is still present.

Thank you

**Closed by cedricdelpoux** 2020-12-04 15:22 UTC
