### ISSUE TITLE
  TypeError: Cannot destructure property `inlineObjectId` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by shaunchander** [cedricdelpoux/gatsby-source-google-docs#55] opened 2020-04-03 03:36 UTC
I'm receiving the following error when running `yarn develop` after adding gatsby-source-google-docs to my project: 
```
TypeError: Cannot destructure property `inlineObjectId` of 'undefined' or 'null'.

  - converters.js:56 getImage
    [google-docs-test]/[gatsby-source-google-docs]/utils/converters.js:56:15

  - converters.js:130 getCover
    [google-docs-test]/[gatsby-source-google-docs]/utils/converters.js:130:38

  - converters.js:142 convertGoogleDocumentToJson
    [google-docs-test]/[gatsby-source-google-docs]/utils/converters.js:142:17

  - google-docs.js:43 google.docs.documents.get
    [google-docs-test]/[gatsby-source-google-docs]/utils/google-docs.js:43:15

  - apirequest.js:43 createAPIRequestAsync.then.r
    [google-docs-test]/[googleapis-common]/build/src/apirequest.js:43:53

  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7
```

I was able to successfully get an access token, my `.google` folder is at the root of my project, and my `gatsby-config.json` file is valid (pasted below)

```
module.exports = {
  siteMetadata: {
    title: `Gatsby Default Starter`,
    description: `Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.`,
    author: `@gatsbyjs`,
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/gatsby-icon.png`, // This path is relative to the root of the site.
      },
    },
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.dev/offline
    // `gatsby-plugin-offline`,
    "gatsby-source-google-docs",
    {
      resolve: "gatsby-transformer-remark",
      options: {
        plugins: ["gatsby-remark-images"],
      },
    },
  ],
}

```

I'm just trying to test this plugin with a dummy Google Doc in my GDrive, there's no images in it, just lorem ipsum text. 

Any possible solutions to this?

**Comment by cedricdelpoux** [comment] 2020-04-03 05:46
I will investigate.  Thank you for reporting this

**Comment by cedricdelpoux** [comment] 2020-04-03 06:14
@shaunchander could you share with me a public GoogleDrive folder I can use to reproduce ? 

```
{
      resolve: "gatsby-source-google-docs",
      options: {
        folders: ["YOUR_FOLDER_ID"],
        debug: true,
      },
    },
```

**Comment by cedricdelpoux** [comment] 2020-04-03 06:20
Could you also  try to move the `gatsby-source-google-docs` config at the top of your plugins list?

**Comment by linoxyn** [comment] 2020-04-03 16:22
I had mentioned I was getting the `undefined` image error as stated above in @shaunchander  post. I believe this happened because a few of my Docs do not have an image in the header. As a test I have added an image to the header to the Docs that had no image. My development ran with no error after this change, yet I have yet to clean up my former query structure to take in the `...GatsbyImageSharpFluid` query. 

When I look at your code, it seems it should be fine in recognizing an image may be null and should safely return null.

Here is the basic query and return example I get in GraphiQL when all Docs have an image in the header.
```
query MyQuery {
  allMarkdownRemark(filter: {frontmatter: {category: {eq: "Established Living Contemporary"}}}) {
    edges {
      node {
        frontmatter {
          cover {
            image {
              childImageSharp {
                fluid {
                  src
                }
              }
            }
          }
        }
      }
    }
  }
}
```
Output:
```
{
  "data": {
    "allMarkdownRemark": {
      "edges": [
        {
          "node": {
            "frontmatter": {
              "cover": {
                "image": {
                  "childImageSharp": {
                    "fluid": {
                      "src": "/static/cbadfd300439e5163cbd8886ab09a202/dee3b/google-docs-image-ba80ca39-e57d-5606-a43c-c8bb72f31003.jpg"
                    }
                  }
                }
              }
            }
          }
        },
        {
          "node": {
            "frontmatter": {
              "cover": {
                "image": {
                  "childImageSharp": {
                    "fluid": {
                      "src": "/static/dd3126c47e6f60d0de67f43dcdbef86a/dee3b/google-docs-image-17b0e1ef-f38b-5e4d-8778-fc5175fd6dee.jpg"
                    }
                  }
                }
              }
            }
          }
        },
        {
          "node": {
            "frontmatter": {
              "cover": {
                "image": null
              }
            }
          }
        },
        {
          "node": {
            "frontmatter": {
              "cover": {
                "image": {
                  "childImageSharp": {
                    "fluid": {
                      "src": "/static/e69d267fb4a5de7eb3e1cd517e520987/dee3b/google-docs-image-a5e44c8e-a460-5bc1-8ef6-f3fe0d8640a4.jpg"
                    }
                  }
                }
              }
            }
          }
        },
        {
          "node": {
            "frontmatter": {
              "cover": {
                "image": null
              }
            }
          }
        },
        {
          "node": {
            "frontmatter": {
              "cover": {
                "image": {
                  "childImageSharp": {
                    "fluid": {
                      "src": "/static/aa4c865edcc45871bfb4d69eacc4c172/dee3b/google-docs-image-8440bc64-29f3-5031-bdab-217fd01fc7cf.jpg"
                    }
                  }
                }
              }
            }
          }
        },
(cropped)
```
Is it normal here to get the `"image": null` returns periodically from the query? Could this possibly come from empty editing containers left over from editing the Google Docs? 
Another question, Is it possible to return more than one image, an array or multiple nodes, from one Doc file with two or more images inserted in the one header?

thanks.

**Comment by shaunchander** [comment] 2020-04-03 19:18
> @shaunchander could you share with me a public GoogleDrive folder I can use to reproduce ?
> 
> ```
> {
>       resolve: "gatsby-source-google-docs",
>       options: {
>         folders: ["YOUR_FOLDER_ID"],
>         debug: true,
>       },
>     },
> ```

I can, https://drive.google.com/drive/folders/1L7hTeYRb09vdw0uzQUdfNv-Ql1DIl-0o?usp=sharing

**Comment by linoxyn** [comment] 2020-04-03 19:35
> Tried this, same error as before.

Edit your Doc. Insert/Headers & Footers/Header. Then check `Different first page`. Insert an image into the header section. Run develop and it should work. Query in GraphiQL.

**Comment by cedricdelpoux** [comment] 2020-04-04 12:44
@shaunchander @linoxyn Could you try the `2.0.0-beta.6`? It should fix the issue

**Comment by linoxyn** [comment] 2020-04-04 19:35
@cedricdelpoux I have updated the version to `2.0.0-beta.6` and I am now able to query the `cover` field. No errors, though I have yet to rewrite my code within the template files to reflect the new image queries based on `cover`. In your [example code snippet](https://github.com/cedricdelpoux/gatsby-source-google-docs/blob/master/docs/faq.md#how-can-i-add-a-cover) you are filtering the `fields: {path}` on `markdownRemark` though the field called `fields` does not show for me in the GraphiQL Explorer. Should that field show?

```
export const pageQuery = graphql`
  query BlogPost($path: String!) {
     post: markdownRemark(fields: {path: {eq: $path}}) {
        html
       frontmatter {
         cover {
            image {
              childImageSharp {
                fluid(maxWidth: 200, quality: 100) {
                  ...GatsbyImageSharpFluid
                }
              }
            }
          }
       }
     }
  }
`
```  
thank you

**Comment by linoxyn** [comment] 2020-04-05 13:37
I have worked more with the files and now some Docs in this shared folder `1hZkvKrrpsBimMVrhCe3pesSn-azHrKyZ` are returning the `cover` image as `null` even though I believe the image is properly added to the header. I have rebuilt the Docs when one or more fail to return query data for the `cover`, this fixes the issue but only temporarily when other Docs that worked before now fail. It's difficult to know if there's a pattern to this behaviour.

I have noticed when I run develop there are two warnings, though I'm not sure if they are related to this issue when the page returns `TypeError: Cannot read property 'childImageSharp' of null` 

Two warnings when gatsby develop is run:
```
warn Plugin `gatsby-transformer-remark` tried to define the GraphQL type `MarkdownRemark`, which has already been defined by the plugin `gatsby-source-google-docs`.
warn Multiple node fields resolve to the same GraphQL field `MarkdownRemark.frontmatter.cover.image` - [`image___NODE`, `image`]. Gatsby will use `image___NODE`.
```
thank you

**Comment by cedricdelpoux** [comment] 2020-04-06 09:36
@linoxyn you should try query `post: markdownRemark(frontmatter: {path: {eq: $path}}) {` instead.

I updated the documentation

**Comment by cedricdelpoux** [comment] 2020-04-06 09:37
I'm aware of the warnings. I will remove them in the next beta release

**Comment by cedricdelpoux** [comment] 2020-04-06 09:43
@linoxyn  I'm not sure to understand your concern now. Is the issue resolved?

**Comment by linoxyn** [comment] 2020-04-06 16:09
> @linoxyn I'm not sure to understand your concern now. Is the issue resolved?

The issue still persists. When I run clean and develop all the images are generated and added to the `public/static` folder, this is fine and expected.

 I find that in my templates a number of pages do not render as the image queried through `cover` `image` returns `null`.  If continue to run `gatsby clean` and `gatsby develop` the images that return `null` and the images that are properly queried remain the same. Though if I go into my Drive and delete and replace a `null` image returning Doc, that new Doc now returns the image, though now there are other Docs that before returned a cover image now do not. Some may not change their behaviour, and others will now return `null` for the `cover` `image`. Below I show the difference of before and after re-making only the `The Art of the Deal` Doc. Notice the changes using the same query. 
**Before:**
```
{
  "data": {
    "allMarkdownRemark": {
      "edges": [
        {
          "node": {
            "frontmatter": {
              "name": "Tony Luciani's \"The Dressmaker\" awarded 1st prize in the 10th International \"FIGURATIVAS 2019\" Painting & Sculpture Competition",
              "cover": {
                "image": {
                  "childImageSharp": {
                    "fluid": {
                      "src": "/static/b6b22e32190af391318f26013233b9f0/f836f/google-docs-image-21415e6f-3739-5a9d-af33-7a8ff519cf86.jpg"
                    }
                  }
                }
              }
            }
          }
        },
        {
          "node": {
            "frontmatter": {
              "name": "Dr. Roberta Bondar Celebrates 27th Anniversary of Space Launch",
              "cover": {
                "image": null
              }
            }
          }
        },
        {
          "node": {
            "frontmatter": {
              "name": "Tony Luciani \"Inside My Head\" on CBC Radio",
              "cover": {
                "image": null
              }
            }
          }
        },
        {
          "node": {
            "frontmatter": {
              "name": "W. David Ward \"Eyes of Society: Art, Traditional Knowledge, and the Watchmen of Haida Gwaii\"",
              "cover": {
                "image": null
              }
            }
          }
        },
        {
          "node": {
            "frontmatter": {
              "name": "Shannon Craig Morphew: Featured in the Dulwich Picture Gallery's \"In View\" magazine",
              "cover": {
                "image": {
                  "childImageSharp": {
                    "fluid": {
                      "src": "/static/c49446a06709af5cb7f8690051fcdba3/9dc27/google-docs-image-67dbaca4-3db5-5c88-98cf-1af31f9922b1.jpg"
                    }
                  }
                }
              }
            }
          }
        },
        {
          "node": {
            "frontmatter": {
              "name": "The Art of the Deal",
              "cover": {
                "image": null
              }
            }
          }
        },
        {
          "node": {
            "frontmatter": {
              "name": "The Art of Salesmanship",
              "cover": {
                "image": {
                  "childImageSharp": {
                    "fluid": {
                      "src": "/static/383aa78c3dc0f0577654850811045a7b/f836f/google-docs-image-46f9aa55-5cf3-5b3c-9843-414a873bc323.jpg"
                    }
                  }
                }
              }
            }
          }
        },
        {
          "node": {
            "frontmatter": {
              "name": "A rare painting by Paul Kane sets a new record for Canadian Art",
              "cover": {
                "image": {
                  "childImageSharp": {
                    "fluid": {
                      "src": "/static/0e7b00dbf0b14341895f15204283608f/f836f/google-docs-image-d842c567-1655-5729-bc01-50029971b1b7.jpg"
                    }
                  }
                }
              }
            }
          }
        }
      ]
    }
  }
}
```
**After re-making one Doc:**
```
{
  "data": {
    "allMarkdownRemark": {
      "edges": [
        {
          "node": {
            "frontmatter": {
              "name": "Tony Luciani's \"The Dressmaker\" awarded 1st prize in the 10th International \"FIGURATIVAS 2019\" Painting & Sculpture Competition",
              "cover": {
                "image": null
              }
            }
          }
        },
        {
          "node": {
            "frontmatter": {
              "name": "Dr. Roberta Bondar Celebrates 27th Anniversary of Space Launch",
              "cover": {
                "image": {
                  "childImageSharp": {
                    "fluid": {
                      "src": "/static/96369c2d10bd5db831e4e649bbe18067/35801/google-docs-image-b8dc15bc-2c29-5485-a2a1-28974390b952.jpg"
                    }
                  }
                }
              }
            }
          }
        },
        {
          "node": {
            "frontmatter": {
              "name": "Tony Luciani \"Inside My Head\" on CBC Radio",
              "cover": {
                "image": null
              }
            }
          }
        },
        {
          "node": {
            "frontmatter": {
              "name": "W. David Ward \"Eyes of Society: Art, Traditional Knowledge, and the Watchmen of Haida Gwaii\"",
              "cover": {
                "image": {
                  "childImageSharp": {
                    "fluid": {
                      "src": "/static/df87e419d6e9da4ce2c6645e189e1870/ea029/google-docs-image-10faf1b7-e60c-5144-80ab-0c0ba66b12ee.jpg"
                    }
                  }
                }
              }
            }
          }
        },
        {
          "node": {
            "frontmatter": {
              "name": "Shannon Craig Morphew: Featured in the Dulwich Picture Gallery's \"In View\" magazine",
              "cover": {
                "image": {
                  "childImageSharp": {
                    "fluid": {
                      "src": "/static/c49446a06709af5cb7f8690051fcdba3/9dc27/google-docs-image-4ffba19d-bbb4-509f-bcfc-e1e08f404d63.jpg"
                    }
                  }
                }
              }
            }
          }
        },
        {
          "node": {
            "frontmatter": {
              "name": "The Art of the Deal",
              "cover": {
                "image": {
                  "childImageSharp": {
                    "fluid": {
                      "src": "/static/c48a9a2c19722a9a43e32c0db0569c84/f836f/google-docs-image-98ce7765-489c-5866-b827-7a34d3de3047.jpg"
                    }
                  }
                }
              }
            }
          }
        },
        {
          "node": {
            "frontmatter": {
              "name": "The Art of Salesmanship",
              "cover": {
                "image": null
              }
            }
          }
        },
        {
          "node": {
            "frontmatter": {
              "name": "A rare painting by Paul Kane sets a new record for Canadian Art",
              "cover": {
                "image": null
              }
            }
          }
        }
      ]
    }
  }
}
```
thank you

**Comment by cedricdelpoux** [comment] 2020-04-08 15:57
For now, I can't explain what happen. I will need help on this.
@linoxyn Could you open a new issue with the content of your comments?

I close this issue because the problem is somewhere else

**Closed by cedricdelpoux** 2020-04-08 15:57 UTC
