### ISSUE TITLE
message: EISDIR: illegal operation on a directory, write

### ISSUE THREAD

**Issue by ccbenavides** [cedricdelpoux/gatsby-source-google-docs#63] opened 2020-06-09 07:31 UTC
"message: EISDIR: illegal operation on a directory, write" last message when i put credentials,

specs: 
npm 6.14.5
node v12.18.0
os: windows 10 pro

**Comment by linoxyn** [comment] 2020-06-10 00:46
My set up has the same versions except just Windows 10.  All packages in a very simple Gatsby app are all up to date. On a `gatsby develop` I was prompted to generate a token as it was now seen as missing after updating the `gatsby-source-google-docs` plugin. I now get this same error. I have tried a number of 'fixes' I found from web searches, nothing has worked so far.

**Comment by cedricdelpoux** [comment] 2020-06-11 16:23
@linoxyn Are you using `Windows` too?

I can't reproduce on `MacOs`

**Comment by cedricdelpoux** [comment] 2020-06-11 16:31
@linoxyn @ccbenavides I think I fixed the bug!

Could you try the `2.0.0-beta.11` version?

**Comment by linoxyn** [comment] 2020-06-11 18:56
@cedricdelpoux I have updated the version to `2.0.0-beta.11` the same error message occurs. Do you recommend any steps that you see as a prerequisite which may clean things up that may help resolve this?

**Comment by cedricdelpoux** [comment] 2020-06-12 04:51
If the last run created a .env folder, you have to remove it

**Comment by linoxyn** [comment] 2020-06-12 16:33
I had not realized that this .env folder was there. I removed it and ran the token command which completed successfully. Running develop or build after this gave me an error that the token was missing. Previously in this test sample project I had been setting up Firebase Firestore and to set .env variables I set two files `.env.development` and `.env.production` using **GATSBY_** as a prefix for them. This was working before the update and because gatsby includes dotenv I did not need to provide 
```
require('dotenv').config({
  path: `.env.${process.env.NODE_ENV || 'development'}`,
})
```
in the `gatsby-config.js` file. Now it is needed in the config file and I have had to copy the `GATSBY_SOURCE_GOOGLE_DOCS_TOKEN` variable into both  `.env.development` and `.env.production` files and also keep the generated `.env` file. 

It seems to be working as is now in development though later I will have to see what may happen when this web app is built and deployed to Firebase Webhosting where the environment variables will need to work.

Thank you for your help

**Comment by cedricdelpoux** [comment] 2020-06-12 17:08
I removed the `.google` folder where was previously stored the token to be `Gatsby Cloud` compliant. You can remove your `.google` folder now. It's deprecated. I forgot to update the docs too. My bad.

Now, the `generate-token` script add the token to the `.env` file. Indeed, if you have more than one `.env` file, you have to copy. I forgot about that. Maybe it could be automatic. What do you think?

**Comment by linoxyn** [comment] 2020-06-12 19:27
I did remove the `.google` folder as I saw it wasn't needed, yes, I agree it would be best to update the docs :-) 

I've only recently started to dig into using `.env.*` files and to some extent I do understand their basic use, though it does become more complex when trigger builds and cloud hosting are involved. Though to keep things more seamless I would agree that automatically writing to the used `.env.*` file(s) would be very good.

I will add that I've successfully tested a build and then firebase deploy. Eventually I will be attempting to set up Github Actions to set up a better workflow.

**Comment by cedricdelpoux** [comment] 2020-06-16 15:01
I don't know how to detect and retrieve all `.env.*` files. Do you know a way?

**Comment by linoxyn** [comment] 2020-06-16 18:37
This may be of help [Glob](https://www.npmjs.com/package/glob) in getting the `.env.*` files into an array. 
And [this](https://dev.to/sergchr/tricks-on-writing-appending-to-a-file-in-node-1hik) looks like a useful article on appending to the files.

**Comment by cedricdelpoux** [comment] 2020-06-17 13:11
I did not know about `glob` package. Thank you I will try

**Comment by cedricdelpoux** [comment] 2020-06-17 14:07
It should be good! Thank you for your help. 

I'm closing this issue now.

**Closed by cedricdelpoux** 2020-06-17 14:07 UTC
